spring:
  application:
    name: store
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 2h change back to 5m or 300
    refreshTokenExpiration: 604800 # 7d
  profiles:
    active: dev
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
