-- Categories
INSERT INTO categories (name)
VALUES ('Dairy'),
       ('Bakery'),
       ('Beverages'),
       ('Produce'),
       ('Meat'),
       ('Frozen Foods'),
       ('Snacks'),
       ('Breakfast'),
       ('Pantry'),
       ('Household');

-- Products
INSERT INTO products (name, price, description, category_id)
VALUES ('Organic Valley Whole Milk 1 Gallon',
        5.49,
        'Organic whole milk from Organic Valley. One gallon container.',
        1),
       ('Pepperidge Farm Farmhouse Sourdough Bread',
        4.29,
        'Soft sliced sourdough bread ideal for sandwiches and toast.',
        2),
       ('Coca-Cola Original Taste 12-Pack',
        8.99,
        'Twelve 12-ounce cans of Coca-Cola Original Taste soda.',
        3),
       ('Bananas',
        1.79,
        'Fresh ripe bananas sold per bunch.',
        4),
       ('Tyson Boneless Skinless Chicken Breast',
        9.99,
        'Fresh boneless skinless chicken breasts, approximately 1.5 lb package.',
        5),
       ('Ben & Jerry''s Chocolate Fudge Brownie Ice Cream',
        6.49,
        'Chocolate ice cream with brownie pieces in a pint container.',
        6),
       ('Lay''s Classic Potato Chips 8 oz',
        4.79,
        'Classic salted potato chips in an 8-ounce bag.',
        7),
       ('Cheerios Original Cereal',
        5.99,
        'Whole grain oat cereal suitable for breakfast.',
        8),
       ('Barilla Spaghetti No. 5',
        2.29,
        'Italian spaghetti pasta made from durum wheat semolina.',
        9),
       ('Bounty Select-A-Size Paper Towels 6 Rolls',
        14.99,
        'Absorbent paper towels with six double rolls.',
        10);